### PR TITLE
Platform agnostic Zookeeper path building

### PR DESCRIPTION
**Pull request by patrikn**
This fixes a problem where Zookeeper paths are built using "\" when run on Windows.

### CODE REVIEW

**Comment by avsej** [comment]
Does it work with having clients both on windows and Linux? And when zookeeper is on Linux but one of the clients on windows?

And why not java.nio.file.Path?

**Comment by patrikn** [comment]
Since the fix always generates the same path regardless of platform I see no reason why it wouldn't work with client and server running on different platforms, but we only test on all-Windows, all-Linux and all-OS X setups.

The reason for not using Path is that I don't see any point to it here - the purpose of Path is to hide differences between different file systems or platforms, but here the platform is always ZooKeeper so the path should always use "/". I guess if the bucket name contains "/" there could be a problem, but it doesn't seem like java.nio.file.Path does any escaping, either.

**Comment by avsej** [comment]
So why does it use external lib to join parts with slashes the?

**Comment by patrikn** [comment]
I didn't realise it was a transitive dependency, replaced with StringBuilder now. It will take some time before I have this actually tested, but I'm fairly confident it will work the same as the Joiner version.

**Pull request closed without merging**
